// ? CATEGORY CONSTANT TYPES
export const FETCH_CATEGORY_REQUEST = "FETCH_CATEGORY_REQUEST";
export const FETCH_CATEGORY_SUCCESS = "FETCH_CATEGORY_SUCCESS";
export const FETCH_CATEGORY_FAILOUR = "FETCH_CATEGORY_FAILOUR";

// ? SET DEFAULT CATEGORY
export const SET_DEFAULT_CATEGORY = "SET_DEFAULT_CATEGORY";
